# -*- coding: utf-8 -*-
"""ai_resume_analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g63QbKL76yMoahfR2JX7kx5ZRcPL8QC0
"""

import json

def analyze_resume(resume_text):
    # Simple keyword matching for job roles
    keywords = {
        "Data Scientist": ["machine learning", "data analysis", "python", "statistics"],
        "Software Engineer": ["programming", "java", "python", "software development"],
        "Product Manager": ["product strategy", "market analysis", "leadership"],
        "Cybersecurity Analyst": ["network security", "encryption", "risk assessment"],
        "AI Specialist": ["deep learning", "neural networks", "computer vision"]
    }

    scores = {role: sum(1 for word in words if word in resume_text.lower())
              for role, words in keywords.items()}

    best_match = max(scores, key=scores.get)
    return {"best_match": best_match, "scores": scores}

if __name__ == "__main__":
    resume = input("Paste your resume text here: ")
    result = analyze_resume(resume)
    print(json.dumps(result, indent=4))